
[ChampionGuard]
DeployTimeChangesDeployAnim=true
IngamePathfindVisible=true


[Firecracker]
TryToFinishAttackAnimation=true

[Valkyrie]
TryToFinishAttackAnimation=true

[TriWizard]
OnStartingAction = "TriWizardCharSpawn"

[ElectroGiant]
HasDamageVisualPivot = false

[Giant]
OnStartingAction="ImmuneToWeakPushback"

[Pekka]
OnStartingAction="ImmuneToWeakPushback"

[Golem]
OnStartingAction="ImmuneToWeakPushback"

[Prince]
OnStartingAction="ImmuneToWeakPushback"

[GiantSkeleton]
OnStartingAction="ImmuneToWeakPushback"

[RoyalGiant]
OnStartingAction="ImmuneToWeakPushback"

[DarkPrince]
OnStartingAction="ImmuneToWeakPushback"

[LavaHound]
OnStartingAction="ImmuneToWeakPushback"

[ZapMachine]
OnStartingAction="ImmuneToWeakPushback"

[Bowler]
OnStartingAction="ImmuneToWeakPushback"

[MovingCannon]
OnStartingAction="ImmuneToWeakPushback"

[MegaKnight]
OnStartingAction="ImmuneToWeakPushback"

[GoblinGiant]
OnStartingAction="ImmuneToWeakPushback"

[ElixirGolem1]
OnStartingAction="ImmuneToWeakPushback"

[MightyMiner]
OnStartingAction="ImmuneToWeakPushback"

[ElectroGiant]
OnStartingAction="ImmuneToWeakPushback"

[SuperLavaHound]
OnStartingAction="ImmuneToWeakPushback"

[SkeletonKing]
OnStartingAction="ImmuneToWeakPushback"

[SuperLavaHound2]
OnStartingAction="ImmuneToWeakPushback"

[Prince_Chess]
OnStartingAction="ImmuneToWeakPushback"

[PrinceBuff]
OnStartingAction="ImmuneToWeakPushback"

